/*Author: Jose Aguirre
 * Created on July 11, 2015, 11:28 AM
 * Class: C++
 * Purpose: Project One
 * A four letter code game
*/

#include <iostream> //I/O Library
#include <cstdlib>//header library includes random numbers
#include <ctime>//header file for time 0 since 1970
using namespace std;//Namespace for iostream
void greeting();//greets players 
char guess();//#game
void goodBye();//says bye to players
int main() 
{
	//variable declarations
    char ans; 
    //loops greeting and game
    do{
        greeting();//this function generates a random hello
        guess();
    //prompt user to continue playing
    cout << "Play Again?" << endl
         << "Enter Y to retry," << endl
         << "any other key to end game." << endl; 
    //user inputs y to play again and any other key to stop     
    cin >> ans; 
    }    
    while(ans == 'y' or ans == 'Y');
    //generate a random bye-bye message
    goodBye();
    return 0; 
}
/******************************************************
 ***************** guess *****************************
 ******************************************************
 * Purpose: Runs the game and the iterations(guesses user gets).
 * Input: User inputs: a or b or c or d or e
 * Output: If first input is correct user inputs 
 * second guess, or else user keeps trying the first letter
 * If user does not guess in the amount required, the game ends. 
 *      
 */
char guess()
{
	//variable declarations
    //for loop, i is used for the number of iterations
    int i;
    //for the size of our array
    const int SIZE=5;
    //the 4 different letters the user will input
    char guess1,guess2,guess3, guess4;
    //the 4 dif letters the computer will generate
    int rndm1,rndm2,rndm3,rndm4; 
    //the letters used in this game
    char letter[SIZE]={'a','b','c','d','e'};
    //time 0 makes rand truly random 
    //rndm1-4 will correspond to an element in the array
    srand(time(0));
    rndm1 = (rand()%5);
    rndm2 = (rand()%5);
    rndm3 = (rand()%5);
    rndm4 = (rand()%5);
    
    //output program's purpose and prompt user input
    cout<<"This is a guessing game."<<endl
            <<"The objective of the game is that you"<<endl
            <<"guess a code which is generated by the computer."<<endl
            <<"The code is four characters in length and is"<<endl
            <<"made up of only the first five letters of the alphabet."<<endl
            <<"Those characters are: a, b, c, d, e"<<endl
            <<endl
            <<"For example, a four letter code might be: "<<endl
            <<"adec"<<endl<<"or"<<endl<<"adda"<<endl<<"or even"<<endl<<"bbbb"<<endl;
        cout<<"Enter your first letter: "<<endl;
    //enter the loop
    //all four letters
    //iterations is set < SIZE
    for(i=1; i<SIZE; i++)
    {    
        cin>> guess1;
        if(guess1!=letter[rndm1])
        {
            cout<<"Try again!"<< endl; 
        }
        if(guess1==letter[rndm1])
            {
            for(i=1;i<SIZE;i++)
            {
                cout<<"1st letter correct."<<endl;
                cout<<"1st letter: "<<guess1<<endl;
                cout<<"2nd letter: "; 
                cin>>guess2; 
                if(guess2!=letter[rndm2])
                {
                    cout<<"Try again!"<<endl;
                }
                if(guess2==letter[rndm2])
                for(i=1;i<SIZE;i++)
                {
                    cout<<"1st & 2nd letter correct."<<endl;
                    cout<<"1st letter: "<<guess1<<endl;
                    cout<<"2nd letter: "<<guess2<<endl; 
                    cout<<"3rd letter: ";
                    cin>>guess3; 
                    if(guess3!=letter[rndm3])
                    cout<<"Try again!"<<endl; 
                    if(guess3==letter[rndm3])
                    for(i=1;i<SIZE;i++)
                    {
                        cout<<"1st & 2nd & 3rd letter correct."<<endl;
                        cout<<"1st letter: "<<guess1<<endl;
                        cout<<"2nd letter: "<<guess2<<endl; 
                        cout<<"3rd letter: "<<guess3<<endl; 
                        
                        cout<<"4th letter: ";
                        cin>>guess4; 
                        if(guess4!=letter[rndm4])
                        cout<<"Try again!"<<endl; 
                        if(guess4==letter[rndm4])

                            {
                            cout << "Winner!"<<endl;
                            cout<<"CODE: ";
                            cout<<letter[rndm1]<<letter[rndm2]<<letter[rndm3]<<letter[rndm4]; 
                            cout<<endl; 
                            return -1; 
                            }
                    }
                }
            } 
        }           
    }
    cout<<"You loose"<<endl;
}
/******************************************************
 ***************** greeting *****************************
 ******************************************************
 * Purpose:  To display a greeting message
 * Input:
        Void funnction, no input necessary
 * Output:
 *      greeting
 */
void greeting()
{
    srand(time(0));//to make the program truly generate a random greeting
    int num;
    num = (1+rand()%4); //+1 bc 0 is not a valid entry
    //cout << num; I did this to trace bc could not figure out where 0 was coming from(%)
        switch (num)
        {
            case 1: 
                cout << "Hi!" << endl; 
                break; 
            case 2: 
                cout << "Hola!" << endl; 
                break; 
            case 3: 
                cout << "Welcome!" << endl; 
                break; 
            case 4: 
                cout << "Yo! Yo! Yo!" << endl; 
                break;
            default: 
                cout <<"Not valid entry" << endl; //it will generate zero
        }
    
}
/******************************************************
 ***************** goodBye *****************************
 ******************************************************
 * Purpose:  To display a farewell message and exit game
 * Input:
        any key other than 'y'
 * Output:
 *      farewell message
 */
void goodBye()
{
    srand(time(0));//to make the program truly generate a random greeting
    int num;
    num = (1+rand()%5); //+1 bc 0 is not a valid entry
    //cout << num; I did this to trace bc could not figure out where 0 was coming from(%)
        switch (num)
        {
            case 1: 
                cout << "Good-bye!" << endl; 
                break; 
            case 2: 
                cout << "Smell ya later!" << endl; 
                break; 
            case 3: 
                cout << "See you later!" << endl; 
                break; 
            case 4: 
                cout << "Hasta la vista" << endl; 
                break;
            case 5:
                cout << "Thank you, come again!" << endl; 
                break; 
            default: 
                cout <<"Not valid entry" << endl; //it will generate zero
        }
}
